[package]
name = "soma-sensor-broker"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[[bin]]
name = "soma-sensor-broker"
path = "src/main.rs"

[dependencies]
image      = { version = "0.25", default-features = false, features = ["jpeg"] }
rmp-serde  = "1"
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
zenoh      = "1"
tokio      = { version = "1", features = ["rt-multi-thread", "macros", "sync", "io-util", "io-std"] }
uuid       = { version = "1", features = ["v4"] }
